import init from "./js/init-observable";
import fromArr from "./js/from-array";
import fromEvent from "./js/from-event";
import range from "./js/from-range";
import fromInterval from "./js/from-interval";
import swMap from "./js/switchMap";
import mgMap from "./js/mergeMap";
import ccMap from "./js/concatMap";

console.log("#1 ==========");
init();
console.log("#2 ==========");
fromArr();
console.log("#3 ==========");
fromEvent();
console.log("#4 ==========");
range();
console.log("#5 ==========");
fromInterval();
console.log("#6 ==========");
swMap();
console.log("#7 ==========");
mgMap();
console.log("#8 ==========");
ccMap();